title: Sundaytoz 기술 블로그 
email: help@sundaytoz.com
description: >- # this means to ignore newlines until "baseurl:"
  선데이토즈 사내 기술 블로그입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://sundaytoz.github.io
timezone: Asia/Seoul

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-feed
  

# Paginate settings
permalink: /:year/:month/:day/:title/
paginate_path: '/page/:num/'
paginate: 10
# pagination:
#   enabled: true
#   per_page: 10
#   sort_reverse: true
#   sort_field: 'date'
#   title: ':title'



# Directories path settings 
file_url: /files
sidebar_url: /files/sidebar
category_dir: category/
tag_dir: tags/


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
